#include <liblpc40xx/peripherals/adc.test.cpp>                // NOLINT
#include <liblpc40xx/peripherals/can.test.cpp>                // NOLINT
#include <liblpc40xx/peripherals/dac.test.cpp>                // NOLINT
#include <liblpc40xx/peripherals/eeprom.test.cpp>             // NOLINT
#include <liblpc40xx/peripherals/gpio.test.cpp>               // NOLINT
#include <liblpc40xx/peripherals/i2c.test.cpp>                // NOLINT
#include <liblpc40xx/peripherals/pwm.test.cpp>                // NOLINT
#include <liblpc40xx/peripherals/spi.test.cpp>                // NOLINT
#include <liblpc40xx/peripherals/system_controller.test.cpp>  // NOLINT
#include <liblpc40xx/peripherals/uart.test.cpp>               // NOLINT
